apiVersion: v1
kind: ConfigMap
metadata:
  name: csgo-tournament
  namespace: csgo
data:
  admins_simple.ini: |
    // Tournament admins
    // Dago
    "STEAM_0:0:11464313" "z"

    // Olivertj
    "STEAM_0:0:67063141" "z"

    // Server team
    // Mark
    "STEAM_0:0:119943" "z"
    // Nicolai
    "STEAM_0:0:866497" "z"
    // Brian
    "STEAM_0:0:777440" "z"
    // Martin
    "STEAM_0:1:23731081" "z"
    // Kristian
    "STEAM_0:1:3563023" "z"
