apiVersion: v1
kind: Pod
metadata:
  name: csgo-test
  labels:
    app: csgo-test
spec:
  nodeName: "161739"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - image: timche/csgo
    name: csgo-test
    env:
    - name: CSGO_DISABLE_BOTS
      value: "true"
    - name: CSGO_GSLT
      value: "6130C8F3A2D6C94EDF37A66044BA2D1C"
    - name: CSGO_MAX_PLAYERS
      value: "12"
    - name: CSGO_PARAMS
      value: "+sv_hibernate_when_empty 0 +sv_logecho 1 +log on +con_logfile /dev/stdout -condebug -secure"
    volumeMounts:
    - mountPath: /home/csgo/server
      name: csgo-volume
  volumes:
  - name: csgo-volume
    hostPath:
      # directory location on host
      path: /home/npfuser
      # this field is optional
      type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: csgo-test
spec:
  selector:
    app: csgo-test
  ports:
    - protocol: TCP
      port: 27015
      targetPort: 27015
---
apiVersion: v1
kind: Service
metadata:
  name: csgo-test
spec:
  selector:
    app: csgo-test
  ports:
    - name: gametcp
      protocol: TCP
      port: 27015
      targetPort: 27015
    - name: gameudp
      protocol: UDP
      port: 27015
      targetPort: 27015
    - name: matchandhltvtcp
      protocol: TCP
      port: 27020
      targetPort: 27020
    - name: matchandhltvudp
      protocol: UDP
      port: 27020
      targetPort: 27020
