name: npflan-release

on:
  release:
    types: [released]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build vanilla
        uses: docker/build-push-action@v2
        with:
          context: npflan
          push: true
          tags: npflan/docker-csgo:vanilla, npflan/docker-csgo:vanilla-${{ github.event.release.tag_name }}
          target: vanilla
      -
        name: Build ebot
        uses: docker/build-push-action@v2
        with:
          context: npflan
          push: true
          tags: npflan/docker-csgo:ebot, npflan/docker-csgo:ebot-${{ github.event.release.tag_name }}
          target: ebot
      -
        name: Build get5
        uses: docker/build-push-action@v2
        with:
          context: npflan
          push: true
          tags: npflan/docker-csgo:get5, npflan/docker-csgo:get5-${{ github.event.release.tag_name }}
          target: get5