name: npflan-ci

on:
  push:
    branches:
      - 'master'
      - 'change-startup-script'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build vanilla
        uses: docker/build-push-action@v2
        with:
          context: npflan
          push: false
          tags: npflan/docker-csgo:vanilla-${{ steps.date.outputs.date }}
          target: vanilla
      -
        name: Build ebot
        uses: docker/build-push-action@v2
        with:
          context: npflan
          push: false
          tags: npflan/docker-csgo:ebot-${{ steps.date.outputs.date }}
          target: ebot
      -
        name: Build get5
        uses: docker/build-push-action@v2
        with:
          context: npflan
          push: false
          tags: npflan/docker-csgo:get5-${{ steps.date.outputs.date }}
          target: get5